In [2]:
import numpy as np

In [3]:
arr=np.array([1,7,32,81,99,43,85,2])

In [4]:
arr

array([ 1,  7, 32, 81, 99, 43, 85,  2])

In [7]:
list_of_lists=([1,2,5],[5,7,9],[11,17,19])
np.array(list_of_lists)

array([[ 1,  2,  5],
       [ 5,  7,  9],
       [11, 17, 19]])

In [9]:
np.arange(4,18)

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [10]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
np.arange(1,58,6)

array([ 1,  7, 13, 19, 25, 31, 37, 43, 49, 55])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [14]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [24]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [27]:
np.zeros((2,10),int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [28]:
np.linspace(0,1,7)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [29]:
np.linspace(0,56,8)

array([ 0.,  8., 16., 24., 32., 40., 48., 56.])

In [30]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.random.rand(3,2)

array([[0.21686683, 0.14014068],
       [0.20562042, 0.96092226],
       [0.40676336, 0.25844796]])

In [33]:
np.random.randint(52,100)

72

In [35]:
np.random.randint(52,100,75)

array([78, 66, 74, 62, 73, 86, 98, 95, 56, 99, 77, 95, 71, 94, 71, 79, 95,
       89, 54, 75, 81, 83, 60, 81, 64, 89, 68, 90, 97, 76, 87, 76, 87, 66,
       60, 85, 91, 88, 83, 55, 57, 80, 90, 83, 99, 74, 75, 66, 92, 67, 88,
       60, 59, 92, 52, 77, 70, 95, 67, 67, 67, 66, 70, 98, 88, 76, 90, 87,
       80, 78, 84, 70, 65, 77, 80])

In [36]:
sample_array=np.arange(38)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37])

In [37]:
rand_array=np.random.randint(0,80,15)

In [38]:
rand_array

array([ 5, 18, 11, 39,  4, 18,  1, 73, 17, 74,  9,  1, 67, 41, 32])

In [39]:
sample_array.reshape(6,5)

ValueError: cannot reshape array of size 38 into shape (6,5)

In [41]:
sample_array.reshape(19,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37]])

In [42]:
rand_array.min()

1

In [44]:
rand_array.max()

74

In [46]:
rand_array.argmax()

9

In [47]:
rand_array.argmin()

6

In [48]:
sample_array.dtype

dtype('int32')

In [57]:
pa=np.eye(9)

In [55]:
pa

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [58]:
pa.T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [60]:
pa=np.random.rand(6,12)

In [61]:
pa

array([[0.96817409, 0.45365387, 0.11515732, 0.02125969, 0.80361891,
        0.25829554, 0.70679895, 0.54613179, 0.22068048, 0.1030097 ,
        0.74540163, 0.43457273],
       [0.08042857, 0.53416985, 0.02576968, 0.09575544, 0.74732037,
        0.96432139, 0.47491652, 0.28961192, 0.73450433, 0.19800825,
        0.89507299, 0.37316707],
       [0.66544575, 0.72944867, 0.04443604, 0.12581944, 0.25737573,
        0.73737731, 0.34402646, 0.20689109, 0.29962076, 0.69752873,
        0.34906619, 0.53288977],
       [0.41556357, 0.8234346 , 0.43360627, 0.45862407, 0.41138474,
        0.82066871, 0.19562163, 0.44438716, 0.45922605, 0.67476631,
        0.53119964, 0.31547619],
       [0.19202801, 0.78581333, 0.32970359, 0.10161391, 0.81297921,
        0.27760824, 0.07159299, 0.38037438, 0.03840714, 0.05802289,
        0.86092207, 0.91763199],
       [0.51416543, 0.29604313, 0.3860983 , 0.8907939 , 0.1741392 ,
        0.97889446, 0.51254467, 0.92568845, 0.22478374, 0.04491561,
        0.9441104 ,

In [70]:
sample_array=np.arange(10,21)

sample_array

In [69]:
sample_array[3:7]

array([13, 14, 15, 16])

In [71]:
sample_array[3]

13

In [73]:
sample_array[1:4]=69
sample_array

array([10, 69, 69, 69, 14, 15, 16, 17, 18, 19, 20])

In [78]:
sample_array=np.arange(10,12)
sample_array

array([10, 11])

In [85]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11])

In [86]:
subset_sample_array[1:4]=1069
subset_sample_array

array([  10, 1069])

In [90]:
subset_sample_array[:]=777
subset_sample_array

array([777, 777])

###                  TWO-DIMENSIONAL ARRAY

In [134]:
sample_matrix=np.array([[50,56,89,21],[123,452,542,974],[12,67,890]])
sample_matrix

C:\Users\Pavan\AppData\Local\Temp\ipykernel_3548\373461672.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  sample_matrix=np.array([[50,56,89,21],[123,452,542,974],[12,67,890]])


array([list([50, 56, 89, 21]), list([123, 452, 542, 974]),
       list([12, 67, 890])], dtype=object)

In [99]:
sample_matrix[1][2]

542

In [100]:
sample_matrix[2]

[12, 67, 890]

In [133]:
sample_matrix[:,(1,2)]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [107]:
sample_array=np.arange(1,20)

In [108]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [109]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [111]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [112]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [113]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [114]:
np.max(sample_array)

19

In [115]:
np.min(sample_array)

1

In [116]:
np.argmax(sample_array)

18

In [117]:
np.argmin(sample_array)

0